########################################
# Goal constants                       #
########################################

# Action name used to addess the server
string DEFAULT_ACTION_NAME=riemo_move_plan_action

########################################
# Goal definition                      #
########################################

# 3D target position
geometry_msgs/Point target

bool use_upright_orientation_constraint
bool use_upright_orientation_constraint_end_only

# Note on format: <v{x,y,z}> denotes a vector and <pt{x,y,z}> denotes a point.
string approach_constraint_csv # Format: <vx>,<vy>,<vz>
string obstacle_linearization_constraint_csv # Format: <vx>,<vy>,<vz>,<t_fraction>
string passthrough_constraint_csv # Format: <ptx>,<pty>,<ptz>,<radius>,<t_fraction>

---

########################################
# Result definition                    #
########################################

#
# Planners result data
#

# currently not needed

---

########################################
# Feedback definition                  #
########################################

#
# Planning feedback data
#
#

# currently not needed
